Official Check In
eclipse-tractusx/emergingtechnologies pull request #5
Opened 2024-07-15 10:37 UTC by felixatdlr

## Description

Final check-in of the emerging technologies repository.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ X ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ X ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-07-18 11:21 UTC, SebastianBezold commented
Project contribution issue opened: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15736

2024-07-18 12:55 UTC, SebastianBezold requested changes
Hi @felixatdlr,

there is a small adoption to the `NOTICE.md` that you should do.
Please also consider some top level `README.md` content.
The project contribution IP issue is already closed in the meantime

2024-07-18 12:55 UTC, SebastianBezold commented on NOTICE.md
> +* https://github.com/eclipse-tractusx/sig-infra
This should point to this repo instead of `sig-infra`

2024-07-18 12:55 UTC, SebastianBezold commented on README.md
I would at least mention, that this repository is hosting a collection of topics that have been worked on by the "emerging technologies" team during consortia phase and link to the `README.md` files in the sub-directories

2024-07-23 08:48 UTC, felixatdlr commented on README.md
Done, see https://github.com/eclipse-tractusx/emergingtechnologies/pull/6

2024-07-23 08:48 UTC, felixatdlr commented on NOTICE.md
> +* https://github.com/eclipse-tractusx/sig-infra
Updated, see https://github.com/eclipse-tractusx/emergingtechnologies/pull/5/commits/b18d4e6ceb40360da5986b7f9f0e9e71f553abdc

2024-07-23 09:05 UTC, SebastianBezold approved these changes

2024-07-23 09:05 UTC, merged